---
title: "presentation transcript"
output:
  word_document: default
  html_document: default
---

# title 

Good afternoon everyone, I am glad to be here to present our findings regarding food choices at different timing among UK adults. 

# COI

We have no conflict of interest to declare. 

# P3 (Background/objectives)

It has been shown that eating late or having a late dinner is associated with obesity and diabetes. The relationship between food choice and their time of consumption is largely left unknown. 

Our aim was to look at the relationships between food groups and the time they were eaten, and how such associations may vary by diabetes status.


# P4 (Data source - the NDNS RP)

The data was from the UK National Diet and Nutrition Survey, nearly 7000 adults were included in our anlaysis. Altogether, we had about 750,000 food recordings collected with a 4-day food diary.

Times slots over the day were defined as seven intervals over the day (as shown here). 


# P5 (Methods and strategies)

We used correspondence analysis as a tool for data mining, visualisation and hypotheses generation. Biplots that graphically showing the association between time of day and food groups were derived for all adults and seprately according to their diabetes status. 

Half of the food recordings were randomly selected for generating hypotheses, and the other half were used for testing. 

Afterwards, logistic regression models with generalised estimating equation that account for repeated measurements were used to test generated hypotheses, comparing the odds of being consumed later at night to earlier time in the day. 


# P6, P7, P8, P9裏面

An example of a one-day food diary is shown here. 

Time intervals was defined according to the diary. Time, location, name of foods and preparation details were asked to recorded.

# P10 

The definitions of diabetes and numbers of subjects are shown in this Table. 

# P11

There are 60 standard food groups in the data, this table shows the frequency of these foods recorded in the dataset, and their percentages of calorie contribution. 28 types of food contributed 80% of total energy. 

# P12 

Full contingency table of food and time slots are shown in this table. 
You may also realize that it is not possible to see any relationship by simply looking at the table. 

# P13-P14 (total sample CA biplot)

These figures here show the potential associations between time and food groups by the defined diabetes status. 

Correspondence analysis allows us to plot both the points of time and food in the same figure where here we see later time are in the upper side of the graph. And when food and time points are close together and away from the origin then it is suggested that there is an association. The association is considered to be higher if the distance between food, time is further from the origin.


- Therefore, in the graph, food appears close to the time, means they were consumed at that time.

- It seems that later time in the day (8 pm- 10pm-) are shown on the upper side of the plot. (later time slots (8pm - 10pm, 10pm - 6am) are different from the earlier hours) 

- During morning time people are having breakfast foods (cereals/milk)

- Chocolate, Beer, Spirits, sugar candy, sweetened soft drinks are clouded around later times. 


# P15, P16, P17, P18, P19, P20

Similar to biplot created for the total sample, later time in the day (8 pm and later) appear in the upper side of each figure and potentially had association with alcoholic beverages and highly processed or energy condense food groups. Some foods and time slots flagged up associations differed by diabetes status.

For example, puddings moved towards closer to later time in undiagnosed DM patients. Furthermore, sugar confectionery, regular soft drinks, chocolates and etc. appear much further at the top of the figures among non diagnosed diabetes patients compared to the other participants. 

We colored those food for further hypotheses testing in red as they are considered to be relatively unhealthy and possibly being consumed differently by diabetes status in terms of the timing. 

# P21 

The results from testing these hypotheses are listed in this table. Apparently, all chosen unhealthy foods had higher odds of being consumed between 8pm to 6am than ealier time. Especially, for people with undiagnosed diabetes, they had 12 times higher odds of eating sugar confectionery, and nearly 2 times higher odds of drinking sweetened soft drink during the night time than earlier time, whereas the associations were weaker among the the other participants. 

# P22-P23


In conclusion, highly processed and easily accessible foods and drinks are more likely to be consumed in the evening. Un-diagnosed diabetes patients are likely to be caused as they chose to have a number of less healthy foods at night. These information might be helpful in identifying public health targets for behaviour change/modification.

Thanks for listening and I am happy to take any quesitions. 

